//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakOtomasyonuProje.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Category_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string ProductImageName1 { get; set; }
        public string ProductImageName2 { get; set; }
        public string ProductImageName3 { get; set; }
        public string ProductImageName4 { get; set; }
        public string ProductImageName5 { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int oda { get; set; }
        public int metreKare { get; set; }
        public int kId { get; set; }
        public Nullable<int> kat { get; set; }
        public bool state { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Category Category { get; set; }
    }
}
